// <auto-generated />
using System;
using Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIController.Migrations
{
    [DbContext(typeof(BienalDbContext))]
    [Migration("20241012220954_MigracionEscultor")]
    partial class MigracionEscultor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entidades.Escultores", b =>
                {
                    b.Property<int>("EscultorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EscultorId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Biografia")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Contraseña")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Foto")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("EscultorId");

                    b.ToTable("Escultores");
                });

            modelBuilder.Entity("Entidades.Esculturas", b =>
                {
                    b.Property<int>("EsculturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EsculturaId"));

                    b.Property<int>("EscultorID")
                        .HasColumnType("int");

                    b.Property<int?>("EscultoresEscultorId")
                        .HasColumnType("int");

                    b.Property<int>("EventoID")
                        .HasColumnType("int");

                    b.Property<string>("Imagenes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("EsculturaId");

                    b.HasIndex("EscultoresEscultorId");

                    b.ToTable("Esculturas");
                });

            modelBuilder.Entity("Entidades.Esculturas", b =>
                {
                    b.HasOne("Entidades.Escultores", null)
                        .WithMany("Esculturas")
                        .HasForeignKey("EscultoresEscultorId");
                });

            modelBuilder.Entity("Entidades.Escultores", b =>
                {
                    b.Navigation("Esculturas");
                });
#pragma warning restore 612, 618
        }
    }
}
